name = "Inflector"
uuid = "6d011eab-0732-4556-8808-e463c76bf3b6"
authors = ["Adrian Salceanu <e@essenciary.com> and contributors"]
version = "1.0.0"

[deps]
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
